version: '3.8'

services:
  influx:
    image: influxdb:1.8.10
    restart: always
    volumes:
      - .:/app
    ports:
      - "8086:8086"

  # main:
  #   build: .
  #   restart: always
  #   volumes:
  #     - .: /app
  