version: '3.8'

services:
  influx:
    image: influxdb:1.8.10
    restart: always
    volumes:
      - .:/app
    ports:
      - "8086:8086"

  cache:
    image: redis:latest
    restart: always

  bot:
    build: .
    restart: always
    volumes:
      - .:/app
    command: python main.py
  